# Use an official GCC image from Docker Hub
FROM gcc:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Default command to run when the container starts
CMD ["bash"]
