CREATE TABLE states (
    id SERIAL PRIMARY KEY,
    state_name VARCHAR(100) NOT NULL,
    capital VARCHAR(100) NOT NULL
);

INSERT INTO states (state_name, capital) VALUES
('Alabama', 'Montgomery'),
('Alaska', 'Juneau'),
('Arizona', 'Phoenix'),
('Arkansas', 'Little Rock'),
('California', 'Sacramento'),
('Colorado', 'Denver'),
('Connecticut', 'Hartford'),
('Deleware', 'Dover'),
('Florida', 'Tallahassee'),
('Georgia', 'Atlanta'),
('Hawaii', 'Honolulu'),
('Idaho', 'Boise'),
('Illinoise', 'Springfield'),
('Indiana', 'Indianapolis'),
('Iowa', 'Des Moines'),
('Kansas', 'Topeka'),
('Kentucky', 'Frankfort'),
('Louisiana', 'Baton Rouge'),
('Maine', 'Augusta'),
('Maryland', 'Annapolis'),
('Massachusetts', 'Boston'),
('Michigan', 'Lansing'),
('Minnesota', 'St. Paul'),
('Mississippi', 'Jackson'),
('Missouri', 'Jefferson City'),
('Montana', 'Helena'),
('Nebraska', 'Lincoln'),
('Nevada', 'Carson City'),
('New Hampshire', 'Concord'),
('New Jersey', 'Trenton'),
('New Mexico', 'Santa Fe'),
('New York', 'Albany'),
('North Carolina', 'Raleigh'),
('North Dakota', 'Bismarck'),
('Ohio', 'Columbus'),
('Oklahoma', 'Oklahoma City'),
('Oregon', 'Salem'),
('Pennsylvania', 'Harrisburg'),
('Rhode Island', 'Providence'),
('South Carolina', 'Columbia'),
('South Dakota', 'Pierre'),
('Tennessee', 'Nashville'),
('Texas', 'Austin'),
('Utah', 'Salt Lake City'),
('Vermont', 'Monntpelir'),
('Virginia', 'Richmond'),
('Washington', 'Olympia'),
('West Virginia', 'Charleston'),
('Wisconsin', 'Madison'),
('Wyoming', 'Cheyenne');
