services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/memory_game_db
    volumes:
      - .:/app  # Mount the current directory to the container's /app directory
      - /app/node_modules  # Avoid conflicts with host node_modules
    depends_on:
      - db
    container_name: memory-game-app
    command: npm start  # Use npm start to run the application

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memory_game_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: memory-game-db

volumes:
  db_data:
